### ISSUE TITLE
Compile error on v8-debug

### ISSUE THREAD

**Issue by halton** [toxic-johann/is-pwa-ready#8]
I'm on latest master HEAD 27737522f901a9c9f2ae4fa6d6c39196e2a833e4, but fail to build with below message.

Node.js version: v9.9.0
OS: Ubuntu 16.04.4 LTS 64-bit
```
$ npm install 

> v8-debug@1.0.1 preinstall /home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug
> node -e 'process.exit(0)'


> v8-debug@1.0.1 install /home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v59-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@9.9.0 (node-v59 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::Call(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:41:20: warning: ‘static v8::MaybeLocal<v8::Value> v8::Debug::Call(v8::Local<v8::Context>, v8::Local<v8::Function>, v8::Local<v8::Value>)’ is deprecated: No longer supported [-Wdeprecated-declarations]
         v8::Debug::Call(context, fn);
                    ^
In file included from /home/halton/.node-gyp/9.9.0/include/node/v8.h:26:0,
                 from /home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:8,
                 from ../src/debug.cc:1:
/home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:193:42: note: declared here
                 static MaybeLocal<Value> Call(
                                          ^
/home/halton/.node-gyp/9.9.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/debug.cc:41:36: warning: ‘static v8::MaybeLocal<v8::Value> v8::Debug::Call(v8::Local<v8::Context>, v8::Local<v8::Function>, v8::Local<v8::Value>)’ is deprecated: No longer supported [-Wdeprecated-declarations]
         v8::Debug::Call(context, fn);
                                    ^
In file included from /home/halton/.node-gyp/9.9.0/include/node/v8.h:26:0,
                 from /home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:8,
                 from ../src/debug.cc:1:
/home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:193:42: note: declared here
                 static MaybeLocal<Value> Call(
                                          ^
/home/halton/.node-gyp/9.9.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::SendCommand(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:52:45: warning: ‘static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)’ is deprecated: Use v8-inspector [-Wdeprecated-declarations]
         Isolate* debug_isolate = v8::Debug::GetDebugContext(Isolate::GetCurrent())->GetIsolate();
                                             ^
In file included from /home/halton/.node-gyp/9.9.0/include/node/v8.h:26:0,
                 from /home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:8,
                 from ../src/debug.cc:1:
/home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:209:39: note: declared here
                 static Local<Context> GetDebugContext(Isolate* isolate));
                                       ^
/home/halton/.node-gyp/9.9.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/debug.cc:52:82: warning: ‘static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)’ is deprecated: Use v8-inspector [-Wdeprecated-declarations]
         Isolate* debug_isolate = v8::Debug::GetDebugContext(Isolate::GetCurrent())->GetIsolate();
                                                                                  ^
In file included from /home/halton/.node-gyp/9.9.0/include/node/v8.h:26:0,
                 from /home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:8,
                 from ../src/debug.cc:1:
/home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:209:39: note: declared here
                 static Local<Context> GetDebugContext(Isolate* isolate));
                                       ^
/home/halton/.node-gyp/9.9.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/debug.cc:57:20: warning: ‘static void v8::Debug::SendCommand(v8::Isolate*, const uint16_t*, int, v8::Debug::ClientData*)’ is deprecated: No longer supported [-Wdeprecated-declarations]
         v8::Debug::SendCommand(debug_isolate, *command, command.length());
                    ^
In file included from /home/halton/.node-gyp/9.9.0/include/node/v8.h:26:0,
                 from /home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:8,
                 from ../src/debug.cc:1:
/home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:170:29: note: declared here
                 static void SendCommand(Isolate* isolate,
                             ^
/home/halton/.node-gyp/9.9.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/debug.cc:57:73: warning: ‘static void v8::Debug::SendCommand(v8::Isolate*, const uint16_t*, int, v8::Debug::ClientData*)’ is deprecated: No longer supported [-Wdeprecated-declarations]
         v8::Debug::SendCommand(debug_isolate, *command, command.length());
                                                                         ^
In file included from /home/halton/.node-gyp/9.9.0/include/node/v8.h:26:0,
                 from /home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:8,
                 from ../src/debug.cc:1:
/home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:170:29: note: declared here
                 static void SendCommand(Isolate* isolate,
                             ^
/home/halton/.node-gyp/9.9.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::RunScript(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:71:51: warning: ‘static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)’ is deprecated: Use v8-inspector [-Wdeprecated-declarations]
         Local<Context> debug_context = v8::Debug::GetDebugContext(Isolate::GetCurrent());
                                                   ^
In file included from /home/halton/.node-gyp/9.9.0/include/node/v8.h:26:0,
                 from /home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:8,
                 from ../src/debug.cc:1:
/home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:209:39: note: declared here
                 static Local<Context> GetDebugContext(Isolate* isolate));
                                       ^
/home/halton/.node-gyp/9.9.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/debug.cc:71:88: warning: ‘static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)’ is deprecated: Use v8-inspector [-Wdeprecated-declarations]
         Local<Context> debug_context = v8::Debug::GetDebugContext(Isolate::GetCurrent());
                                                                                        ^
In file included from /home/halton/.node-gyp/9.9.0/include/node/v8.h:26:0,
                 from /home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:8,
                 from ../src/debug.cc:1:
/home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:209:39: note: declared here
                 static Local<Context> GetDebugContext(Isolate* isolate));
                                       ^
/home/halton/.node-gyp/9.9.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/debug.cc:78:11: error: ‘GetMirror’ is not a member of ‘v8::Debug’
           v8::Debug::GetMirror(info.GetIsolate()->GetCurrentContext(), info[0]);
           ^
../src/debug.cc:80:38: warning: ‘static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)’ is deprecated: Use v8-inspector [-Wdeprecated-declarations]
           debug_context = v8::Debug::GetDebugContext(Isolate::GetCurrent());
                                      ^
In file included from /home/halton/.node-gyp/9.9.0/include/node/v8.h:26:0,
                 from /home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:8,
                 from ../src/debug.cc:1:
/home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:209:39: note: declared here
                 static Local<Context> GetDebugContext(Isolate* isolate));
                                       ^
/home/halton/.node-gyp/9.9.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/debug.cc:80:75: warning: ‘static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)’ is deprecated: Use v8-inspector [-Wdeprecated-declarations]
           debug_context = v8::Debug::GetDebugContext(Isolate::GetCurrent());
                                                                           ^
In file included from /home/halton/.node-gyp/9.9.0/include/node/v8.h:26:0,
                 from /home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:8,
                 from ../src/debug.cc:1:
/home/halton/.node-gyp/9.9.0/include/node/v8-debug.h:209:39: note: declared here
                 static Local<Context> GetDebugContext(Isolate* isolate));
                                       ^
/home/halton/.node-gyp/9.9.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
debug.target.mk:98: recipe for target 'Release/obj.target/debug/src/debug.o' failed
make: *** [Release/obj.target/debug/src/debug.o] Error 1
make: Leaving directory '/home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/halton/.nvm/versions/node/v9.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-124-generic
gyp ERR! command "/home/halton/.nvm/versions/node/v9.9.0/bin/node" "/home/halton/.nvm/versions/node/v9.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug/build/debug/v1.0.1/node-v59-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug/build/debug/v1.0.1/node-v59-linux-x64"
gyp ERR! cwd /home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/halton/.nvm/versions/node/v9.9.0/bin/node /home/halton/.nvm/versions/node/v9.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug/build/debug/v1.0.1/node-v59-linux-x64/debug.node --module_name=debug --module_path=/home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug/build/debug/v1.0.1/node-v59-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/halton/work/projects/github/is-pwa-ready/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:936:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.4.0-124-generic
node-pre-gyp ERR! command "/home/halton/.nvm/versions/node/v9.9.0/bin/node" "/home/halton/work/projects/github/is-pwa-ready/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug
node-pre-gyp ERR! node -v v9.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/home/halton/.nvm/versions/node/v9.9.0/bin/node /home/halton/.nvm/versions/node/v9.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug/build/debug/v1.0.1/node-v59-linux-x64/debug.node --module_name=debug --module_path=/home/halton/work/projects/github/is-pwa-ready/node_modules/v8-debug/build/debug/v1.0.1/node-v59-linux-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by toxic-johann** [comment]
Check the latest commit~

**Comment by halton** [comment]
thx, verified.
